name: Build and Publish
on: [ push, pull_request ]
jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:

            # Setup Java 1.8 environment for the next steps
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            # Check out current repository
            - name: Fetch Sources
              uses: actions/checkout@v2

            # Build application
            - name: Test and Build
              run: ./gradlew build
